config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get "/dashboard" => "home#dashboard" , as: :dashboard

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  get "/logout" => "sessions#destroy", as: :logout

  resources :champions



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'user_auth'

class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: {with: /@/}

  def to_s
    name
  end

  def token
    UserAuth::Token.encode(id: id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate

  private

  def current_user

    if request.headers['Auth-Token'].present? || request.parameters['auth'].present?

      encoded_token = (request.headers['Auth-Token'].present?) ? request.headers['Auth-Token'].split(' ').last : request.parameters['auth'].split(' ').last
      decoded_token = UserAuth::Token.decode(encoded_token)
      return nil if decoded_token.expired?
      @current_user = User.find(decoded_token[:id]) rescue nil

    else
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]

    end

    return @current_user
  end

  helper_method :current_user

  def authenticate
    respond_to do |format|
      format.html {
        redirect_to(login_path) unless current_user
      }
      format.json {
        render json: {:error => 'you are not authorise to access this.'} unless current_user
      }
    end

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate, only: [:index]

  def index
    require('nasa_open_api')
    api = NasaOpenAPI.new(1000)
    result = api.load_info

    @parsed = result.parsed_response['photos']
    Rails.logger.info("INFO: #{@parsed} ")

  end

  def dashboard

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate
  skip_before_action :verify_authenticity_token, only: [:create]

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user.try(:authenticate, params[:password])
      session[:user_id] = user.id

      respond_to do |format|
        format.html {
          redirect_to dashboard_url, :notice => "Logged in!"
        }
        format.json {
          _user = user.attributes
          _user.delete('password_digest')
          render json: {:user => _user, :token => user.token}
        }
      end
    else
      respond_to do |format|
        format.html {
          flash.now.alert = "Invalid email or password"
          render "new"
        }
        format.json {
          render json: {:error => 'you are not authorise to access this.'}
        }
      end

    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_ALERT_CLASSES = {
    notice: 'alert alert-success',
    alert: 'alert alert-danger',
    error: 'alert alert-danger',
    warning: 'alert alert-warning'
  }

  def bootstrap_alert_class(flash_name)
    BOOTSTRAP_ALERT_CLASSES[flash_name.to_sym]
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/elements/_nav.html.erb
<nav class="navbar navbar-light bg-faded">
  <ul class="nav navbar-nav">
    <li class="nav-item"><%= link_to "Home", root_path, class: "navbar-brand" %></li>

    <% if current_user %>

    <% end %>

    <li class="nav-item">
      <% if current_user %>
        <%= link_to "Log out", logout_path, class: "nav-link" %>
      <% else %>
        <%= link_to "Log in", login_path, class: "nav-link" %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/home/dashboard.html.erb
<h1>Dashboard</h1>

<%= link_to "Champions", champions_path, class: "navbar-brand" %>

app/views/home/index.html.erb
<h1>Home Page</h1>

<% @parsed.each do |photo| %>
  <label>Earth Date:<%= photo['earth_date'] %></label><br/>
  <img width="200" src="<%= photo['img_src'] %>"><br/><br/>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMS Bootstrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render :partial => 'elements/nav' %>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}", class: bootstrap_alert_class(name), role: 'alert' %>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>